name: Selenium TestNG CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

# Dajemo dozvolu GitHub Actions-u da napravi i zapiše report sajt
permissions:
  contents: write

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # Dodat korak koji instalira i osvežava Firefox na GitHub virtuelnoj mašini
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'

    - name: Run TestNG Tests
      env:
        VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
      run: mvn clean test -DsuiteXmlFile=parallel-run.xml
      continue-on-error: true # Ako neki test pukne, želimo da se izveštaj ipak napravi!

    # 1. Korak za preuzimanje istorije prethodnih testova
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      with:
        ref: gh-pages
        path: allure-history
      continue-on-error: true # Sprečava pad ako grana gh-pages još ne postoji

    # 2. Korak koji generiše sam Allure Report iz "target/allure-results" foldera
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history
        keep_reports: 20

    # 3. Korak koji objavljuje taj izveštaj na GitHub Pages grani
    - name: Deploy Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history